apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-editor
  template:
    metadata:
      labels:
        app: video-editor
    spec:
      containers:
      - name: video-editor
        image: gcr.io/video-editor-434002/video-editor:v32
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: PORT
          value: "8000"
        - name: OPENAI_API_KEY
          value: "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"
        volumeMounts:
        - name: output-volume
          mountPath: /app/output
      volumes:
      - name: output-volume
        emptyDir: {}
