apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-editor
  template:
    metadata:
      labels:
        app: video-editor
    spec:
      containers:
      - name: video-editor
        image: gcr.io/video-editor-434002/video-editor:v32
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: PORT
          value: "8000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        volumeMounts:
        - name: output-volume
          mountPath: /app/output
      volumes:
      - name: output-volume
        emptyDir: {}
